Fix PYTHONPATH.
This was causing issues with pip throwing errors about not being able to
build the wheel.  Errors like:

error: invalid command 'bdist_wheel'